2021-10-21 22:10:09,798 INFO    MainThread:11912 [wandb_setup.py:_flush():71] setting env: {}
2021-10-21 22:10:09,798 INFO    MainThread:11912 [wandb_setup.py:_flush():71] setting login settings: {'anonymous': 'must'}
2021-10-21 22:10:09,798 INFO    MainThread:11912 [wandb_init.py:_log_setup():357] Logging user logs to D:\Codes\Pytorch-UNet\wandb\run-20211021_221009-15edgoug\logs\debug.log
2021-10-21 22:10:09,798 INFO    MainThread:11912 [wandb_init.py:_log_setup():358] Logging internal logs to D:\Codes\Pytorch-UNet\wandb\run-20211021_221009-15edgoug\logs\debug-internal.log
2021-10-21 22:10:09,799 INFO    MainThread:11912 [wandb_init.py:init():390] calling init triggers
2021-10-21 22:10:09,799 INFO    MainThread:11912 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-10-21 22:10:09,800 INFO    MainThread:11912 [wandb_init.py:init():435] starting backend
2021-10-21 22:10:09,800 INFO    MainThread:11912 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=spawn, using: spawn
2021-10-21 22:10:09,803 INFO    MainThread:11912 [backend.py:ensure_launched():198] starting backend process...
2021-10-21 22:10:10,003 INFO    MainThread:11912 [backend.py:ensure_launched():203] started backend process with pid: 16060
2021-10-21 22:10:10,004 INFO    MainThread:11912 [wandb_init.py:init():444] backend started and connected
2021-10-21 22:10:10,006 INFO    MainThread:11912 [wandb_init.py:init():503] updated telemetry
2021-10-21 22:10:10,032 INFO    MainThread:11912 [wandb_init.py:init():533] communicating current version
2021-10-21 22:10:10,403 INFO    MainThread:11912 [wandb_init.py:init():538] got version response 
2021-10-21 22:10:10,403 INFO    MainThread:11912 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-10-21 22:10:40,410 INFO    MainThread:11912 [interface.py:_communicate_run():903] couldn't get run from backend
2021-10-21 22:10:40,410 ERROR   MainThread:11912 [wandb_init.py:init():553] backend process timed out
2021-10-21 22:10:40,410 ERROR   MainThread:11912 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
